version: '3'
services:
  db:
    image: postgres
    ports:
      - "1234:5432"
    environment:
      POSTGRES_DB: vacancies
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
  web:
    build: .
    command: python main.py
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 1234
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
